### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by keawade** [unioncollege-webtech/peter-piper#10]
Under the first extra credit variations countOccurrences is misspelled as countOccurrances in the final line.

**Comment by barberboy** [comment]
Thanks! Feel free also to submit a pull request when you see issues like that.

**Comment by keawade** [comment]
I would have made a pull request but I was in a car driving to Colorado, lol. I had the repo cloned to work on it but I couldn't push or make pull requests at that time.

**Comment by barberboy** [comment]
Oh yeah, well I fixed the bug on my iPhone so no excuses!

**Comment by keawade** [comment]
Haha, I'll see what I can do next time.
